# .render.yaml
services:
  - type: web
    name: portafolio
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app  # o el comando que uses para correr tu 
app
    rootDir: ./  # asegurándote de que use la raíz del proyecto
